### ISSUE TITLE
[QUESTION] Single-step or multi-step?

### ISSUE THREAD

**Issue by pnmartinez** [nityansuman/warren#10]
Hi,

I'd like to know whether on the validation set the model is simply forecasting one step ahead.

Thanks!

**Comment by nityansuman** [comment]
Hi @pnmartinez 

It does single timestep. Models are based on FB's Prophet and it being additive model, these models do not do multi-timestep forecast by default. Although with changes to input and output pipelines, it will be possible using a multi model strategy.
