### ISSUE TITLE
Requitements

### ISSUE THREAD

**Issue by Gitbchri** [nityansuman/warren#28]
When I try to install the requirements through pip install -r REQUIREMENTS.txt
I get an error
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1

Any idea what can have gone wrong?

**Comment by nityansuman** [comment]
Hey, @Gitbchri not sure about this but try using `conda` to create an environment and then install packages.
