### ISSUE TITLE
Always get build dependency error

### ISSUE THREAD

**Issue by octopushugger** [nityansuman/warren#33]
First assumed it was an issue on my windows system then ran into the same problem on collab:
![image](https://user-images.githubusercontent.com/91927383/235558102-fe81b3a1-d74b-4711-b8e6-3476ff5af6a6.png)

**Comment by nityansuman** [comment]
Did you find a fix for this? Looks like an issue with some installation. @octopushugger

**Comment by octopushugger** [comment]
Tried installing the dependencies individually to discover it's a wheel building problem. So either it needs a correctly configured compiler or a Python version that wheels are already built for. I couldn't figure out the compiler or how to tell what version of python available wheels are for.
